### ISSUE TITLE
Request for dataset

### ISSUE THREAD

**Issue by susheemmaurya** [vitoralbiero/face_analysis_pytorch#2]
Hi @vitoralbiero, is there anyway that you could share the dataset?

**Comment by vitoralbiero** [comment]
Thelo @susheemmaurya, unfortunately I cannot share the datasets, but you can download most of them free from the internet.
The list of datasets used are on the Wiki: https://github.com/vitoralbiero/face_analysis_pytorch/wiki/Model-Zoo
