### ISSUE TITLE
Inference data preparation

### ISSUE THREAD

**Issue by IvanBarabanau** [vitoralbiero/face_analysis_pytorch#4]
Hi! You've mentioned that images have to be aligned before model inference, using mtcnn, for instance. As mtcnn provides several options, how images are aligned, could you possibly provide a code example, how do you align them?

**Comment by vitoralbiero** [comment]
Hello @IvanBarabanau,

Thank you for your interest in our work!
To align the images, you could use img2pose, as it is the current face aligner/detector we've been using: https://github.com/vitoralbiero/img2pose
After installing it, just run the ```run_face_alignment.py``` script.

Hope this helps.
